#password.directory: /home/thinhvv/IdeaProjects/java-base-project/api/src/main/resources/pwd
#
#database:
#  url: jdbc:mysql://localhost:3307/demo?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
#  user: root
#  driver.class.name: com.mysql.cj.jdbc.Driver


# app value
token.expiration: 1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: vanthinh98
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true