#password.directory: /home/thinhvv/IdeaProjects/java-base-project/api/src/main/resources/pwd
#
#database:
#  url: jdbc:mysql://localhost:3307/demo?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
#  user: root
#  driver.class.name: com.mysql.cj.jdbc.Driver


# app value
token.expiration: 1
token.secretKey: 12345678

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?serverTimezone=JST&useLegacyDatetimeCode=false&zeroDateTimeBehavior=convertToNull&useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: vanthinh98
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: create.sql
#              create-source: metadata